modLoader = "javafml"
loaderVersion = "[47,)"
license = "${license}"
issueTrackerURL="https://github.com/Syconn/HeroCore/issues"

[[mods]]
modId = "hero"
version = "${version}"
displayName = "${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/Syconn/Syconn-Mod-Updates/refs/heads/main/HeroCore.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/syconns-super-hero-mod"
logoFile = "hero.png"
#credits =
authors = "${mod_author}"
description = '''${description}'''

[[dependencies.hero]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hero]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hero]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
