modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/Syconn/HeroCore-v2/issues/new"
license = "All Rights Reserved"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Syconn"
description = '''
${description}
'''
logoFile = "icon.png"
#logoBlur = false

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.hero]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hero]]
modId="playeranimator"
mandatory=true
versionRange="[1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.hero]]
modId="midnightlib"
mandatory=true
versionRange="[1.9.2,)"
ordering="AFTER"
side="BOTH"
