modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"
issueTrackerURL="https://github.com/Syconn/HeroCore/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}" 
updateJSONURL="https://raw.githubusercontent.com/Syconn/Syconn-Mod-Updates/refs/heads/main/HeroCore.json" 
displayURL="https://www.curseforge.com/minecraft/mc-mods/syconns-super-hero-mod"
logoFile = "${mod_id}.png"
credits = "${credits}"
authors = "${mod_author}" 
description = '''${description}'''

[[dependencies.${mod_id}]]
modId = "forge" 
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"