modLoader = "javafml"
loaderVersion = "[4,)"
license = "${license}"
issueTrackerURL="https://github.com/Syconn/HeroCore/issues"

[[mods]]
modId = "hero"
displayName = "${mod_name}"
author = "Syconn"
updateJSONURL="https://raw.githubusercontent.com/Syconn/Syconn-Mod-Updates/refs/heads/main/HeroCore.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/syconns-super-hero-mod"
logoFile = "hero.png"
#credits =
authors = "${mod_author}"
description = '''${description}'''

[[dependencies.hero]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hero]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hero]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "hero.mixins.json"
