name: Publish 1.20.1
 
on: 
  workflow_dispatch:
  push:
     branches:
       - master       

env:                                              
  MINECRAFT_VERSION: 1.20.1                       
  JAVA_VERSION: 22     
  # VERSION: 1.0.3
  # RELEASE_NAME: V1.0.3
  TYPE: release
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}           

permissions:
  contents: write

jobs:                                             
  build:                                          
    runs-on: ubuntu-latest                        
    steps:                                        
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Get Gradle Version
        uses: BrycensRanch/read-properties-action@v1
        id: version
        with:
          file: gradle.properties
          property: mod_version
          default: 1.0.3
        
      - name: Publish Fabric
        uses: Kir-Antipov/mc-publish@v3.3.0                                   
        with:
          curseforge-id: 326469                                             
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"
          
          modrinth-id: syconns-superhero-mod                                             
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          
          github-tag: "v${{env.VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "V${{steps.version.outputs.version}}-Fabric"                             
          version: "${{steps.version.outputs.version}}"
          version-type: "${{env.TYPE}}"
          changelog-file: CHANGELOG.md
          
          files: |
             fabric/build/libs/hero-fabric-${{steps.version.outputs.version}}.jar

          dependencies: |
             fabric@0.92.3+1.20.1(required){modrinth:P7dR8mSH}{curseforge:306612}#(ignore:github)
             architectury@9.2.14(required){modrinth:architectury-api}{curseforge:419699}#(ignore:github)
             playeranimator@1.0.2-rc1+1.20(required){modrinth:playeranimator}{curseforge:658587}#(ignore:github)

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"

      - name: Publish Forge
        uses: Kir-Antipov/mc-publish@v3.3.0                                   
        with:
          curseforge-id: 326469                                             
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"
          
          modrinth-id: syconns-superhero-mod                                             
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          
          github-tag: "v${{steps.version.outputs.version}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "$V{{steps.version.outputs.version}}-Forge"                             
          version: "${{steps.version.outputs.version}}"
          version-type: "${{env.TYPE}}"
          changelog-file: CHANGELOG.md

          files: |
             forge/build/libs/hero-forge-${{steps.version.outputs.version}}.jar

          dependencies: |
             architectury@9.2.14(required){modrinth:architectury-api}{curseforge:419699}#(ignore:github)
             playeranimator@1.0.2-rc1+1.20(required){modrinth:playeranimator}{curseforge:658587}#(ignore:github)

          loaders: forge
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
          

          
