name: Publish
on: [ pull_request, workflow_dispatch ] 

env:                                              
  MINECRAFT_VERSION: 1.20.1                       
  JAVA_VERSION: 17     
  VERSION: 1.0.3  
  RELEASE_NAME: V1.0.3
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }} 

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write

jobs:
  build:
    # strategy:
    #   matrix:
    #     java: |
    #     17
    #     os: [ubuntu-22.04]
    runs-on: ubuntu-latest
    steps:
      - name: "⬇️ Checkout"
        uses: actions/checkout@v3

      - name: Cache Gradle dependencies
        id: cache-gradle-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/forge/.gradle/caches
            ~/fabric/.gradle/caches
            ~/common/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: "🛂 Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1

      - name: "☕ Setup Jdk ${{ matrix.java }}"
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: "🔃 Use Latest Node.js"
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
        uses: actions/setup-node@v3
        with:
          node-version: latest

      # - name: "🏗️ Build & Release to GitHub"
      #   if: ${{ runner.os == 'Linux' && matrix.java == '17' && (steps.get-next-version.outputs.new-release-published == 'true')  }}
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #   run: npx semantic-release

      - name: "🕵️‍♂️ Collect jars"
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: |
            forge/build/libs/*.jar
            fabric/build/libs/*.jar
            !**/*-@(dev|sources|all|shadow).jar

      - uses: Kir-Antipov/mc-publish@v3.3
        name: "🚀 Publish: Fabric"
        with:
          name: "${{env.RELEASE_NAME}}"                             
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md
          
          curseforge-id: 123456                                             
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"
          
          modrinth-id: 1q2w3e4r                                             
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          
          github-tag: "v${{env.VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          files: fabric/build/libs/!(*-@(dev|sources|all|shadow)).jar
          loaders: fabric
          game-versions: "v${{env.MINECRAFT_VERSION}}"
          java: 17
          dependencies: |
            fabric@0.92.3+1.20.1(required){modrinth:P7dR8mSH}{curseforge:306612}#(ignore:github)
            architectury@9.2.14(required){modrinth:architectury-api}{curseforge:419699}#(ignore:github)
            playeranimator@1.0.2-rc1+1.20(required){modrinth:playeranimator}{curseforge:658587}#(ignore:github)
          # game-version-filter: releases

      - uses: Kir-Antipov/mc-publish@v3.3
        name: "🚀 Publish: Forge"
        with:
          name: "${{env.RELEASE_NAME}}"                             
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md
          
          curseforge-id: 123456                                             
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"
          
          modrinth-id: 1q2w3e4r                                             
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          
          github-tag: "v${{env.VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"
          
          files: forge/build/libs/!(*-@(dev|sources|all|shadow)).jar
          game-versions: "v${{env.MINECRAFT_VERSION}}"
          java: 17
          # game-version-filter: releases

          dependencies: |
            architectury@9.2.14(required){modrinth:architectury-api}{curseforge:419699}#(ignore:github)
            playeranimator@1.0.2-rc1+1.20(required){modrinth:playeranimator}{curseforge:658587}#(ignore:github)
